name: Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ./lambda/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./lambda/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies using npm ci
        run: npm ci
        working-directory: ./lambda

      - name: Test
        run: npm test
        working-directory: ./lambda

  Pulumi:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Restore Cache node_modules
        uses: actions/cache@v2
        with:
          path: ./lambda/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./lambda/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Initialize Pulumi stack
        run: |
          pulumi login
          pulumi stack select main
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi preview
        if: github.event_name == 'pull_request'
        run: |
          pulumi preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi up Auto-Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
